# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65e607a950a80676cb0bf4e55c9633e390fa599165a4bdb31f71affa13c5d86f89e8e92324ec9121e67cbd0867d9df231614c60fc3561fd8d0f2562164208d9b

test:
  secret_key_base: e1c3475c38435d4510bc34bdca757a46774c39a63a55e4ff1cec201695ea86f2476819a4980277e464cb7d3b30b8007e3ce9c4dabcc5c0449922acaa549a88b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
